---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: 192.168.222.1:5000/shell-operator:sriov-vf 
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /sys
      name: sys
  nodeName: worker1
  serviceAccountName: sriov-vf-acc
  volumes:
  - name: sys
    hostPath:
      path: /sys
