---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-vf-acc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriov-vf
rules:
- apiGroups: ["sriov.redhat.com"]
  resources: ["virtualfunctions"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-vf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriov-vf
subjects:
  - kind: ServiceAccount
    name: sriov-vf-acc
    namespace: default
